version: "3.8"

services:

  nginx:
    image: DOCKERHUB_USERNAME/nginx:prod # ⚠ This Must Be Changed
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - mysql_db
      - nestjs      
    ports:
      - 80:80
      - 443:443
    networks:
      - my_network

  nestjs:
    image: DOCKERHUB_USERNAME/nestjs:prod # ⚠ This Must Be Changed
    container_name: nestjs
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - mysql_db
    env_file:
      - .env.prod
    networks:
      - my_network

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    volumes:
      - mysqldb_data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env.prod
    networks:
      - my_network

volumes:
  mysqldb_data:
    driver: local

networks:
  my_network:
    driver: bridge