# Use the latest Nginx image
FROM nginx:latest

# Copy the custom Nginx configuration file into the container
COPY default.conf /etc/nginx/conf.d/default.conf

# Run Nginx in the foreground to keep the container running
CMD ["nginx", "-g", "daemon off;"]